apiVersion: v1
kind: ConfigMap
metadata:
  name: coworkinganalytics-config
data:
  DB_NAME: mydatabase
  DB_USER: myuser
  DB_HOST: postgresql-service
  DB_PORT: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: coworkinganalytics-secret
type: Opaque
data:
  DB_PASSWORD: ZWNobyAtbiBteXBhc3N3b3JkCg==